### ISSUE TITLE
Missing ThrottlingMixin in PhoneDevice (Version 1.13)

### ISSUE THREAD

**Issue by sthasashant** [jazzband/django-two-factor-auth#481]
We were getting null value in column "throttling_failure_count" violates not-null constraint in the final step of setup.

## Current Behavior

![image](https://user-images.githubusercontent.com/33341398/157810992-2568fc34-81b5-41c8-ad6d-117f228ba0d7.png)

## Possible Solution

Missing ThrottlingMixin in the PhoneDevice Model in last version of 1.13.
Earlier as we install django-two-factor-auth version 1.13, ThrottlingMixin as inherited in PhoneDevice Model.
As we fresh install django-two-factor-auth version 1.13 in a new local machine this ThrottlingMixin is missing on the same model.

**Comment by claudep** [comment]
Do you mean 1.13.2 or master branch?

**Comment by claudep** [comment]
It would also help to have a full traceback of the error.

**Comment by claudep** [comment]
Please reopen if you can provide the missing information.

**Comment by AvengerMichael** [comment]
I am getting this same error and I am using version 1.13. I only see this error when I try to access the backup tokens url and it does seem like to me it's an issue with the ThrottlingMixin but not sure what I need to do to fix or resolve this error, any help would be appreciated.

**Comment by claudep** [comment]
Please can you provide a traceback?

**Comment by AvengerMichael** [comment]
Environment:


Request Method: GET
Request URL: http://localhost:8000/account/two_factor/backup/tokens/

Django Version: 3.1.2
Python Version: 3.8.13
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'aisearch',
 'django_otp',
 'django_otp.plugins.otp_static',
 'django_otp.plugins.otp_totp',
 'two_factor']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'csp.middleware.CSPMiddleware',
 'two_factor.middleware.threadlocals.ThreadLocals']



Traceback (most recent call last):
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\query.py", line 429, in get
    raise self.model.DoesNotExist(

During handling of the above exception (StaticDevice matching query does not exist.), another exception occurred:
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (null value in column "throttling_failure_count" violates not-null constraint
DETAIL:  Failing row contains (24, backup, t, 2, null, null).
) was the direct cause of the following exception:
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\views\generic\edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\two_factor\views\core.py", line 587, in get_context_data
    context['device'] = self.get_device()
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\two_factor\views\core.py", line 583, in get_device
    return self.request.user.staticdevice_set.get_or_create(name='backup')[0]
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\fields\related_descriptors.py", line 683, in get_or_create
    return super(RelatedManager, self.db_manager(db)).get_or_create(**kwargs)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\query.py", line 576, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\base.py", line 790, in save_base
    updated = self._save_table(
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\base.py", line 933, in _do_insert
    return manager._insert(
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\MichaelTeixeira\anaconda3\envs\aisearch\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /account/two_factor/backup/tokens/
Exception Value: null value in column "throttling_failure_count" violates not-null constraint
DETAIL:  Failing row contains (24, backup, t, 2, null, null).

**Comment by claudep** [comment]
Thanks, and your exact version of django-two-factor-auth and django_otp?

**Comment by AvengerMichael** [comment]
django-two-factor-auth=1.13 and django_otp=0.8.0

**Comment by claudep** [comment]
Did you try upgrading to latest versions?

**Comment by AvengerMichael** [comment]
I had tried upgrading django-two-factor-auth to 1.13.2 but that didn't do anything, I just tried it after upgrading django_otp and that looks like that did it! Thank you for the help!
