### ISSUE TITLE
ModuleNotFoundError: No module named 'two_factor.plugins'

### ISSUE THREAD

**Issue by pcd1000** [jazzband/django-two-factor-auth#483]
I am trying to setup the Django-two-factor-auth 'example' on my local pc.  I was able to do this in the past (pre-plugins), but now I get the above error when I try to run the initial migration.

Any suggestions as to what I am doing wrong?

**Comment by moggers87** [comment]
What version of Django-two-factor-auth, Django, and Python are you using? Also a traceback would be helpful.

**Comment by pcd1000** [comment]
Hi Matt, Many thanks for looking into this.

Django-two-factor-auth version: 1.13.2. and using the 'example' file from that version.

The problem occurs on initial migrate, the traceback as follows:

Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nb/Documents/dev/two_factor_auth_example/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/nb/Documents/dev/two_factor_auth_example/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/Users/nb/Documents/dev/two_factor_auth_example/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/nb/Documents/dev/two_factor_auth_example/venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/nb/Documents/dev/two_factor_auth_example/venv/lib/python3.8/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'two_factor.plugins'

The two factor INSTALLED APPS in 'example' is:     
'two_factor',
'two_factor.plugins.phonenumber',

If I change this to that suggested in the installation instructions, simply: 'two_factor', it works fine.

**Comment by claudep** [comment]
It would be interesting if you could test with the master branch.

**Comment by pcd1000** [comment]
As far as I can tell it's the same.
It works fine with just 'two_factor' in INSTALLED_APPS, but when I add  'two_factor.plugins.phonenumber' I get the same error: ModuleNotFoundError: No module named 'two_factor.plugins'

**Comment by dcopso** [comment]
This is happening because the plugins directory is not being distributed in the pypi image:

```shell
# pip show -f django-two-factor-auth | grep Version:
Version: 1.13.2
# shows no results
$ pip show -f django-two-factor-auth | grep plugins
```

It looks like the distribution is also including pyc files, which is incorrect:
```shell
$ pip show -f django-two-factor-auth | grep __pycache__ | wc -l
38
```

**Comment by claudep** [comment]
I think there is confusion between 1.13.2 and master. The plugins functionality is in master only, so don't try to setup a project with instructions on master and 1.13.2 source. Hopefully we can release 1.14.0 soonish.

**Comment by pcd1000** [comment]
Many thanks, I look forward to 1.14!

**Comment by rahiel** [comment]
Since version 1.14 is released, can this issue be closed now?

**Comment by Thutmose3** [comment]
I still have this error with 1.14.0

**Comment by Thutmose3** [comment]
Oh my bad! I had created a Django module called two_factor in the past and forgot it was there. Django was of course calling that module!
