### ISSUE TITLE
Missing templatetags folder on PyPI in 1.14.0 release?

### ISSUE THREAD

**Issue by marekmansell** [jazzband/django-two-factor-auth#561]
I have updated to the newest PyPI version `1.14.0` and I started getting template tag errors. Is it possible the templatetags folder is missing in the newest PyPI release?

- [PyPI Download (latest version)](https://pypi.org/project/django-two-factor-auth/#files) -- templatetags folder not present
- [PyPI Download (previous version)](https://pypi.org/project/django-two-factor-auth/1.13.2/#files) -- templatetags folder present

This could also explain #532.

**Error:**

```
[2022-10-15 23:46:35 +0200] [2757137] [ERROR] Error handling request /account/login/
Traceback (most recent call last):
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/defaulttags.py", line 1027, in find_library
    return parser.libraries[name]
KeyError: 'two_factor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/sentry_sdk/integrations/django/templates.py", line 73, in rendered_content
    return real_rendered_content.fget(self)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/defaulttags.py", line 1089, in load
    lib = find_library(parser, name)
  File "/var/www/kurzy-beta/envs3/lib/python3.8/site-packages/django/template/defaulttags.py", line 1029, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'two_factor' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
bootstrap5
cache
courses_extra
debugger_tags
embed_video_tags
highlighting
i18n
indent_text
l10n
log
markdownify
static
syntax_color
tz
user_sessions
widont
```

**Comment by claudep** [comment]
Please read carefully the 1.14.0 release notes, you should find the answer of your problem there.
